version: '3.8'

services:
  nestjs:
    build: ./
    image: nestjs-dynamo-app
    container_name: 'nestjs-app'
    ports:
      - '3000:3000'
    environment:
      - ENDPOINT_URL=http://dynamodb-local:8000
      - NODE_ENV=development
    depends_on:
      - dynamodb-local
    networks:
      - nestjs_network
  
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - '8001:8000'
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    volumes:
      - './docker/dynamodb:/home/dynamodblocal/data'
    networks:
      - nestjs_network

networks:
  nestjs_network: